version: '3.8'

services:
  login-server:
    image: hercules
    build: .
    restart: unless-stopped
    ports:
      - 6900:6900
    volumes:
      - configuration:/build/Hercules/conf/import
      - sql_init:/build/Hercules/sql-files
    command: ["./login-server"]
    depends_on:
      - database

  char-server:
    image: hercules
    build: .
    restart: unless-stopped
    ports:
      - 6121:6121
    volumes:
      - configuration:/build/Hercules/conf/import
      - sql_init:/build/Hercules/sql-files
    command: ["./char-server"]
    depends_on:
      - login-server

  map-server:
    image: hercules
    build: .
    restart: unless-stopped
    ports:
      - 5121:5121
    volumes:
      - configuration:/build/Hercules/conf/import
      - sql_init:/build/Hercules/sql-files
    command: ["./map-server"]
    depends_on:
      - char-server

  database:
    image: mariadb:10.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: hercroot
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok
      MYSQL_DATABASE: ragnarok
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - sql_init:/docker-entrypoint-initdb.d

volumes:
  configuration:
  mysql_data:
  sql_init:
