version: '3.8'

services:
  servers:
    image: hercules
    build: .
    restart: unless-stopped
    ports:
      - 6900:6900
      - 6121:6121
      - 5121:5121
  database:
    image: mariadb:lts
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: hercroot
      MYSQL_USER: ragnarok
      MYSQL_PASSWORD: ragnarok
      MYSQL_DATABASE: ragnarok
      INTERSERVER_USER: wisp
      INTERSERVER_PASSWORD: wisp
    expose:
      - 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - sql_init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
  sql_init:
